artifact_location: /home/mohamad/Desktop/x/mlops-core-web-jupyterlab-server/jupyter-nextjs-example/notebooks/MLflow_Tracking_URI/0
creation_time: 1762090364113
experiment_id: '0'
last_update_time: 1762090364113
lifecycle_stage: active
name: Default
