artifact_uri: file:///pat/to/your/artifact/storage/2a88e84062204ba5a5f54b39f6ae7f84/artifacts
end_time: 1762090366335
entry_point_name: ''
experiment_id: '682050781335662753'
lifecycle_stage: active
run_id: 2a88e84062204ba5a5f54b39f6ae7f84
run_name: funny-steed-386
source_name: ''
source_type: 4
source_version: ''
start_time: 1762090364359
status: 4
tags: []
user_id: mohamad
